#+title: How to Use ox-hugo
#+author: Yoshio Shimano
# 出版した日付
#+date: 2019-04-03
# 更新日を自動的につける
#+hugo_auto_set_lastmod: t
# 見出しをレベル 6 まで出す
#+OPTIONS: H:6 num:nil
#+OPTIONS: toc:1
#+STARTUP: indent
#+hugo_type: post
# 出力するディレクトリ
#+hugo_base_dir: ../..
# 出版するファイル名
#+hugo_section: english/docs
#+OPTIONS: creator:nil author:t
#+LANGUAGE: en
# Hugo tags
#+hugo_tags: Hugo ox-hugo
# Hugo categories
#+hugo_categories: Hugo ox-hugo
#+hugo_custom_front_matter: :thumbnail images/org-to-hugo.svg
#+INFOJS_OPT: view:info toc:nil

* From Org-mode marukup to Markdown
:PROPERTIES:
:EXPORT_DATE: 2019-04-05
:EXPORT_HUGO_SECTION: english/posts
:EXPORT_FILE_NAME: from-org-to-markdown
:EXPORT_OPTIONS: toc:nil num:nil
:ID:       91c8c28c-690b-498b-abea-1d6b3f40bb40
:END:

Here are how ox-hugo convert markups (like bold, mono)
in Org to Markdown.


#+caption: From Org-mode to Markdown
|--------------------+-------------------------------------------------+------------------|
| Org                | Markdown                                        | HTML             |
|--------------------+-------------------------------------------------+------------------|
| =*bold*=           | =**bold**=                                      | *bold*           |
| =/italics/=        | =_italics_=                                     | /italics/        |
| ==monospace==      | =`monospace`=                                   | =monospace=      |
| =~key-binding~=    | =`key-binding`=                                 | ~key-binding~    |
|                    | - if =org-hugo-use-code-for-kbd=  nil [Default] |                  |
| =~key-binding~=    | =<kbd>key-binding</kbd>=                        |                  |
|                    | - if =org-hugo-use-code-for-kbd= is not nil     |                  |
|                    | - To render =<kbd>= tag, needs *CSS*            |                  |
| =+strike-through+= | =~~strike-through~~=                            | +strike-through+ |
| =_underline_=      | =<span class = "underline">underline</span>=    | _underline_      |
|                    | - to render this as underline, *CSS* is needed  |                  |
|--------------------+-------------------------------------------------+------------------|

I have sdet 
=org-hugo-use-code-for-kbd= to =t= :


#+caption: Use <kbd> for key-binding
#+begin_src emacs-lisp
(setq org-hugo-use-code-for-kbd t)
#+end_src

And add CSS styles like this:

#+begin_src css
kbd {
    padding: 0.2rem 0.4rem;
    font-size: 87.5%;
    color: #fff;
    background-color: #212529;
    border-radius: 0.2rem;
}

.underline{
    text-decoration: underline;
}
#+end_src


* Reference to LaTeX math in ox-hugo
:PROPERTIES:
:ID:       ba7e8113-305f-4bfe-b709-6ed60b68aacc
:EXPORT_DATE: 2019-04-02
:EXPORT_HUGO_SECTION: english/posts
:EXPORT_FILE_NAME: use-latex-ref-in-ox-hugo
:EXPORT_OPTIONS: toc:nil num:nil
:END:

In Org-mode, you can reference LaTeX math, with =\ref{eq:1}=,
but in ox-hugo it does not work by default.

This math sinippet:

#+begin_src org
\begin{equation}
\label{eq:01}
y = ax + b
\end{equation}
#+end_src

this puroduces this:

\begin{equation}
\label{eq:01}
y = ax + b
\end{equation}

Here I referece Eq. \ref{eq:02} (=Eq(\ref{eq:02}=).
Without the settings below, this reference does not work.

Make =static/mathjax-config.js= as follows
(take from ox-hugo's test site):


#+caption: static/mathjax-config.js
#+begin_src javascript
window.MathJax = {
    displayAlign: "center",
    displayIndent: "0em",
    "HTML-CSS": { scale: 100,
                  linebreaks: { automatic: "false" },
                  webFont: "TeX"
                },
    SVG: {scale: 100,
          linebreaks: { automatic: "false" },
          font: "TeX"},
    NativeMML: {scale: 100},
    TeX: { equationNumbers: {autoNumber: "AMS"},
           MultLineWidth: "85%",
           TagSide: "right",
           TagIndent: ".8em"
         }
};
#+end_src


And call it from a template which calls Javasctipt
(like layouts/partial/header.html):

#+begin_src html
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
<script src="{{ "mathjax-config.js" | absURL }}"></script>
#+end_src

Lets' reference some equations.

#+begin_src org
\begin{equation}
\label{eq:02}
y = ax + b
\end{equation}
#+end_src


\begin{equation}
\label{eq:02}
\y = ax + b
\end{equation}

Here, referencing Eq. \ref{eq:01}.

* TOC in ox-hugo
:PROPERTIES:
:ID:       fbe1c45a-8b5b-41bf-bb36-260714018c26
:END:
** Do not put TOC in Summary
:PROPERTIES:
:EXPORT_DATE: 2019-04-03
:EXPORT_HUGO_SECTION: english/posts
:EXPORT_FILE_NAME: dont-insert-org-toc-into-summary
:EXPORT_OPTIONS: toc:nil num:nil
:ID:       ffdf3a31-dd96-42c0-bd55-d21ea1f18db3
:END:

By default, The TOC generated by ox-hugo is
inserted into "Summary" in Hugo.

This is how to prebent it
(Taken from ox-hugo test site).

*** Copy summary_minus_toc.html
:PROPERTIES:
:ID:       a03829fa-c4dc-400a-a4bd-638d770c360d
:END:

Copy  [[https://github.com/kaushalmodi/hugo-bare-min-theme/blob/master/layouts/partials/summary_minus_toc.html][=summary_minus_toc.html=]] 
from this site.

-  [[https://github.com/kaushalmodi/hugo-bare-min-theme/blob/master/layouts/partials/summary_minus_toc.html][=summary_minus_toc.html=]] 

=summary_minus_toc.html= looks like this:

#+caption: layouts/partials/summary_minus_toc.html
#+name: list: summary_minus_toc
#+begin_src html
{{- with .Description -}}
    {{- . | markdownify | printf "<p>%s</p>" | safeHTML -}}
{{- else -}}
    {{- $summary_has_org_toc := substr .Content 0 30 | findRE "[\".]ox-hugo-toc" -}}
    {{- if $summary_has_org_toc -}}
        {{- $content_splits := split .RawContent "<!--endtoc-->" -}} <!-- Need to use .RawContent as we will be parsing for 'more' comment later. -->
        <!-- If Org TOC is present, the special comment endtoc would also be present.
             In that case, output only the part *after* that comment as Summary. -->
        {{- $summary_raw := index $content_splits 1 -}}
        {{- $summary_splits := split $summary_raw "<!--more-->" -}}
        {{- if eq (len $summary_splits) 2 -}}
            {{- index $summary_splits 0 | markdownify -}}
        {{- else -}}
            {{- $summary_raw | markdownify | truncate 300 -}}
        {{- end -}}
    {{- else -}}
        <!-- Print the whole Summary if endtoc special comment is not found. -->
        {{- .Summary |  printf "<p>%s</p>" | safeHTML -}}
    {{- end -}}
{{- end -}}
#+end_src

I modified some code as below so that
raw HTML codes are not shown.

#+caption: Modified summary_minus_toc.html
#+begin_src html
{{- with .Description -}}
    {{- . | markdownify | printf "<p>%s</p>" | safeHTML -}}
{{- else -}}
    {{- $summary_has_org_toc := substr .Content 0 30 | findRE "[\".]ox-hugo-toc" -}}
    {{- if $summary_has_org_toc -}}
        {{- $content_splits := split .RawContent "<!--endtoc-->" -}} <!-- Need to use .RawContent as we will be parsing for 'more' comment later. -->
        <!-- If Org TOC is present, the special comment endtoc would also be present.
             In that case, output only the part *after* that comment as Summary. -->
        {{- $summary_raw := index $content_splits 1 -}}
        {{- $summary_splits := split $summary_raw "<!--more-->" -}}
        {{- if eq (len $summary_splits) 2 -}}
            {{- index $summary_splits 0 | markdownify -}}
        {{- else -}}
            {{- $summary_raw | markdownify | plainify | truncate 300 -}}
        {{- end -}}
    {{- else -}}
        <!-- Print the whole Summary if endtoc special comment is not found. -->
        {{- .Summary |  printf "<p>%s</p>" | safeHTML -}}
    {{- end -}}
{{- end -}}
#+end_src

I changed this:

#+begin_src html
{{- $summary_raw | markdownify | truncate 300 -}}
#+end_src

to:

#+begin_src html
{{- $summary_raw | markdownify | plainify | truncate 300 -}}
#+end_src


This works as follows:

- If =#+DESCRIPTION:= exitst, it will be used.
- If ox-hugo has made a TOC (if class =ox-hugo-toc= exists).
  delte it, make "Summary".

*** How to use summary_minus_toc.html
:PROPERTIES:
:ID:       fa856510-e59f-4652-b4e9-2eccbdd0af26
:END:
In a template containig "Summary",
use this code:


#+caption: How to use summary_minus_toc.html
#+begin_src html
{{ partial "summary_minus_toc.html" . }}
#+end_src

** ox-hugo に目次を作成させないようにする
:PROPERTIES:
:ID:       f54a41f9-c239-45a2-8815-3032ee7fd343
:EXPORT_DATE: 2019-04-02
:EXPORT_HUGO_SECTION: japanese/posts
:EXPORT_FILE_NAME: disable-ox-hugo-generated-toc
:EXPORT_OPTIONS: toc:nil num:nil 
:END:

ox-hugo はデフォルトで目次を生成します。
それを止めるには、  =org-hugo-export-with-toc= を =nil= に設定します。
また、 =org-html-use-infojs= が =t= だと、 *常に* 目次が
出力されてしまうので、 =nil= に設定しておきます。

#+caption: ox-hugo に目次を作成させないようにする
#+name: disable-ox-hugo-generated-toc
#+begin_src emacs-lisp
(setq org-hugo-export-with-toc nil)
(setq org-html-use-infojs nil)
#+end_src

各サブツリーで次のようにすると、目次は出力されません:

#+begin_src org
:EXPORT_OPTIONS: toc:nil
#+end_src

各サブツリーで次のようにすると、目次が出力されます:

#+begin_src org
:EXPORT_OPTIONS: toc:t
#+end_src

もしくは、次のようにすると、指定したレベルまでの目次が出ます:

#+begin_src org
:EXPORT_OPTIONS: toc:1
#+end_src





* Details and summary
:PROPERTIES:
:EXPORT_DATE: 2019-04-03
:EXPORT_HUGO_SECTION: japanese/posts
:EXPORT_FILE_NAME: details-and-summary
:EXPORT_OPTIONS: toc:t num:nil
:ID:       b0cf174c-c3a8-4fce-9aac-578b3307c37e
:END:

#+begin_details
ox-hugo を使って Details と Summary を書く方法です。
#+end_details

#+begin_src org
#+begin_details
#+begin_summary
これは Summary
#+end_summary
これは detail
#+end_details
#+end_src



#+begin_details
#+begin_summary
これは Summary
#+end_summary
これは detail
#+end_details


